### ISSUE TITLE
missing info in PNG info - like Hires. fix parameters and etc..

### ISSUE THREAD

**Issue by nikolaiusa** [v0xie/sd-webui-cads#18]
thx, your sd-webui-cads is the best, 

but when i try to read info from png info (Hires. fix parametrers, aesthetic gradients) - no parameters in png info

and I tried to run the IPadapter ControlNet as an experiment, I also got an error.

**Comment by v0xie** [comment]
Should be fixed! Let me know if you run into the same issue.
