### ISSUE TITLE
CADS is only applied to the first image when batch is greater than 1

### ISSUE THREAD

**Issue by CCpt5** [v0xie/sd-webui-cads#4]
Hi, 

First of all, thanks for a unique and fun extension!

One bug I just noticed is that when CADs is enabled and the batch size is greater than 1, CADs is only applied to the first timage of the batch. Expected functionality would be for it to be applied to all image generations in the batch.

I did replicate this issue even w/ all other extensions in my A1111 install disabled. I am using the latest dev branch commit, but I doubt that's related to this issue.

To replice:

1) Enter a simple prompt / enter a seed number (to keep it locked) / set batch size to 3 / Generate Images
2) Enable CADS
3) Generate w/ the same settings as above but w/ CADS enabled
4) Notice that CADS was applied to image 1, but not 2 and 3.

If this turns out to be user error somehow my sincere apologies. Thanks!

**Comment by v0xie** [comment]
Thanks for the report! 
I'm not able to reproduce this behavior on my end. 

What video card do you have? It could be related to generating NaN in the hook.  If you start WebUI with the environment variable "SD_WEBUI_LOG_LEVEL" set to "DEBUG", see if any errors/warnings being thrown by the extension.

A couple other things to try: turn on/off Rescale CFG; change RNG source in options.

Let me know if any of these help ~

**Comment by evanerichards** [comment]
I can confirm I am experiencing this same issue.
If I chose batch count of 4, only the first image is changed. If I do a batch size of 4 however, all the images are changed.

Auto1111 version: [1.6.0] •  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.22  •  gradio: 3.41.2

**Comment by v0xie** [comment]
> I can confirm I am experiencing this same issue. If I chose batch count of 4, only the first image is changed. If I do a batch size of 4 however, all the images are changed.
> 
> Auto1111 version: [1.6.0] •  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.22  •  gradio: 3.41.2

Thanks for this. I was confusing batch count with batch size when trying to reproduce. Should be fixed now.
